/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Post = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'image' : IDL.Opt(ExternalBlob),
});
export const Reel = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'video' : ExternalBlob,
  'creatorId' : IDL.Principal,
  'timestamp' : Time,
});
export const UserProfile = IDL.Record({
  'bio' : IDL.Text,
  'displayName' : IDL.Text,
  'coverPhoto' : IDL.Opt(ExternalBlob),
  'isProfessional' : IDL.Bool,
  'professionalTitle' : IDL.Opt(IDL.Text),
  'avatar' : IDL.Opt(ExternalBlob),
});
export const Comment = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'author' : IDL.Principal,
  'timestamp' : Time,
  'postId' : IDL.Nat,
});
export const DirectMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'read' : IDL.Bool,
  'timestamp' : Time,
  'recipientId' : IDL.Principal,
  'senderId' : IDL.Principal,
});
export const Group = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : Time,
  'creatorId' : IDL.Principal,
  'memberIds' : IDL.Vec(IDL.Principal),
});
export const GroupMessage = IDL.Record({
  'id' : IDL.Nat,
  'content' : IDL.Text,
  'groupId' : IDL.Nat,
  'timestamp' : Time,
  'senderId' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'addGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'checkUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
  'createGroup' : IDL.Func([IDL.Text], [IDL.Nat], []),
  'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'createReel' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
  'deleteGroup' : IDL.Func([IDL.Nat], [], []),
  'deleteReel' : IDL.Func([IDL.Nat], [], []),
  'followUser' : IDL.Func([IDL.Principal], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
  'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
  'getConversation' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(DirectMessage)],
      ['query'],
    ),
  'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
  'getFollowers' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFollowing' : IDL.Func(
      [IDL.Principal],
      [IDL.Vec(IDL.Principal)],
      ['query'],
    ),
  'getFriends' : IDL.Func([IDL.Principal], [IDL.Vec(IDL.Principal)], ['query']),
  'getGroupById' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
  'getGroupMessages' : IDL.Func([IDL.Nat], [IDL.Vec(GroupMessage)], ['query']),
  'getLikesCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
  'getMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
  'getMyUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
  'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
  'getReelsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Reel)], ['query']),
  'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'likeOrUnlikePost' : IDL.Func([IDL.Nat], [], []),
  'loginWithCredentials' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Bool],
      ['query'],
    ),
  'markConversationRead' : IDL.Func([IDL.Principal], [], []),
  'registerWithCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'removeGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'respondToFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
  'sendGroupMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
  'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
  'unfollowUser' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Post = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'image' : IDL.Opt(ExternalBlob),
  });
  const Reel = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'video' : ExternalBlob,
    'creatorId' : IDL.Principal,
    'timestamp' : Time,
  });
  const UserProfile = IDL.Record({
    'bio' : IDL.Text,
    'displayName' : IDL.Text,
    'coverPhoto' : IDL.Opt(ExternalBlob),
    'isProfessional' : IDL.Bool,
    'professionalTitle' : IDL.Opt(IDL.Text),
    'avatar' : IDL.Opt(ExternalBlob),
  });
  const Comment = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'author' : IDL.Principal,
    'timestamp' : Time,
    'postId' : IDL.Nat,
  });
  const DirectMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'read' : IDL.Bool,
    'timestamp' : Time,
    'recipientId' : IDL.Principal,
    'senderId' : IDL.Principal,
  });
  const Group = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : Time,
    'creatorId' : IDL.Principal,
    'memberIds' : IDL.Vec(IDL.Principal),
  });
  const GroupMessage = IDL.Record({
    'id' : IDL.Nat,
    'content' : IDL.Text,
    'groupId' : IDL.Nat,
    'timestamp' : Time,
    'senderId' : IDL.Principal,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addComment' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'addGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'checkUsernameAvailable' : IDL.Func([IDL.Text], [IDL.Bool], ['query']),
    'createGroup' : IDL.Func([IDL.Text], [IDL.Nat], []),
    'createPost' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
    'createReel' : IDL.Func([IDL.Text, ExternalBlob], [IDL.Nat], []),
    'deleteGroup' : IDL.Func([IDL.Nat], [], []),
    'deleteReel' : IDL.Func([IDL.Nat], [], []),
    'followUser' : IDL.Func([IDL.Principal], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
    'getAllReels' : IDL.Func([], [IDL.Vec(Reel)], ['query']),
    'getAllUsers' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getCommentsByPost' : IDL.Func([IDL.Nat], [IDL.Vec(Comment)], ['query']),
    'getConversation' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(DirectMessage)],
        ['query'],
      ),
    'getConversations' : IDL.Func([], [IDL.Vec(IDL.Principal)], ['query']),
    'getFollowers' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFollowing' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getFriends' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(IDL.Principal)],
        ['query'],
      ),
    'getGroupById' : IDL.Func([IDL.Nat], [IDL.Opt(Group)], ['query']),
    'getGroupMessages' : IDL.Func(
        [IDL.Nat],
        [IDL.Vec(GroupMessage)],
        ['query'],
      ),
    'getLikesCount' : IDL.Func([IDL.Nat], [IDL.Nat], ['query']),
    'getMyGroups' : IDL.Func([], [IDL.Vec(Group)], ['query']),
    'getMyUsername' : IDL.Func([], [IDL.Opt(IDL.Text)], ['query']),
    'getPostsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Post)], ['query']),
    'getReelsByUser' : IDL.Func([IDL.Principal], [IDL.Vec(Reel)], ['query']),
    'getUnreadMessageCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'likeOrUnlikePost' : IDL.Func([IDL.Nat], [], []),
    'loginWithCredentials' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Bool],
        ['query'],
      ),
    'markConversationRead' : IDL.Func([IDL.Principal], [], []),
    'registerWithCredentials' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'removeGroupMember' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'respondToFriendRequest' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'sendFriendRequest' : IDL.Func([IDL.Principal], [], []),
    'sendGroupMessage' : IDL.Func([IDL.Nat, IDL.Text], [IDL.Nat], []),
    'sendMessage' : IDL.Func([IDL.Principal, IDL.Text], [], []),
    'unfollowUser' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };