/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Comment {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'postId' : bigint,
}
export interface DirectMessage {
  'id' : bigint,
  'content' : string,
  'read' : boolean,
  'timestamp' : Time,
  'recipientId' : Principal,
  'senderId' : Principal,
}
export type ExternalBlob = Uint8Array;
export interface Group {
  'id' : bigint,
  'name' : string,
  'createdAt' : Time,
  'creatorId' : Principal,
  'memberIds' : Array<Principal>,
}
export interface GroupMessage {
  'id' : bigint,
  'content' : string,
  'groupId' : bigint,
  'timestamp' : Time,
  'senderId' : Principal,
}
export interface Post {
  'id' : bigint,
  'content' : string,
  'author' : Principal,
  'timestamp' : Time,
  'image' : [] | [ExternalBlob],
}
export interface Reel {
  'id' : bigint,
  'title' : string,
  'video' : ExternalBlob,
  'creatorId' : Principal,
  'timestamp' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'bio' : string,
  'displayName' : string,
  'coverPhoto' : [] | [ExternalBlob],
  'isProfessional' : boolean,
  'professionalTitle' : [] | [string],
  'avatar' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addComment' : ActorMethod<[bigint, string], undefined>,
  'addGroupMember' : ActorMethod<[bigint, Principal], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'checkUsernameAvailable' : ActorMethod<[string], boolean>,
  'createGroup' : ActorMethod<[string], bigint>,
  'createPost' : ActorMethod<[string, [] | [ExternalBlob]], undefined>,
  'createReel' : ActorMethod<[string, ExternalBlob], bigint>,
  'deleteGroup' : ActorMethod<[bigint], undefined>,
  'deleteReel' : ActorMethod<[bigint], undefined>,
  'followUser' : ActorMethod<[Principal], undefined>,
  'getAllPosts' : ActorMethod<[], Array<Post>>,
  'getAllReels' : ActorMethod<[], Array<Reel>>,
  'getAllUsers' : ActorMethod<[], Array<Principal>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getCommentsByPost' : ActorMethod<[bigint], Array<Comment>>,
  'getConversation' : ActorMethod<[Principal], Array<DirectMessage>>,
  'getConversations' : ActorMethod<[], Array<Principal>>,
  'getFollowers' : ActorMethod<[Principal], Array<Principal>>,
  'getFollowing' : ActorMethod<[Principal], Array<Principal>>,
  'getFriends' : ActorMethod<[Principal], Array<Principal>>,
  'getGroupById' : ActorMethod<[bigint], [] | [Group]>,
  'getGroupMessages' : ActorMethod<[bigint], Array<GroupMessage>>,
  'getLikesCount' : ActorMethod<[bigint], bigint>,
  'getMyGroups' : ActorMethod<[], Array<Group>>,
  'getMyUsername' : ActorMethod<[], [] | [string]>,
  'getPostsByUser' : ActorMethod<[Principal], Array<Post>>,
  'getReelsByUser' : ActorMethod<[Principal], Array<Reel>>,
  'getUnreadMessageCount' : ActorMethod<[], bigint>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'likeOrUnlikePost' : ActorMethod<[bigint], undefined>,
  'loginWithCredentials' : ActorMethod<[string, string], boolean>,
  'markConversationRead' : ActorMethod<[Principal], undefined>,
  'registerWithCredentials' : ActorMethod<[string, string], undefined>,
  'removeGroupMember' : ActorMethod<[bigint, Principal], undefined>,
  'respondToFriendRequest' : ActorMethod<[Principal, boolean], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'sendFriendRequest' : ActorMethod<[Principal], undefined>,
  'sendGroupMessage' : ActorMethod<[bigint, string], bigint>,
  'sendMessage' : ActorMethod<[Principal, string], undefined>,
  'unfollowUser' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];